### ISSUE TITLE
WEKA detector subpixel resolution

### ISSUE THREAD

**Issue by activevsesi** [trackmate-sc/TrackMate-Weka#1]
@tinevez 
Dear Jean-Yves,
First of all, I would like to thank you for your kind efforts to expand the trackmate capabilities for handling complex situations. 
We have been using the WEKA detector to extract lipid membranes' mechanical properties (e.g., bending rigidity and tension of vesicles). Our workflow follows: we first track the contour of the giant vesicles and then extract the mechanical properties from Fourier analysis. But we are unable to get the subpixel resolution of contour with the WEKA detector, I would appreciate it if you could help in this regard.
Thanks,
With regards,
Rao.

**Comment by tinevez** [comment]
Hello @activevsesi 

TrackMate-Weka cannot generate sub-pixel accuracy contour. It is a pixel based segmentation technique.

What you can do is to refine the contours obtained with Weka using __e.g._ active contours, but TrackMate does not do that by itself.
